import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Users,
  Calendar,
  ArrowRight,
  Heart,
  Lightbulb,
  Globe,
} from "lucide-react";

const successStories = [
  {
    id: 1,
    title: "Rural Water Purification System Reaches 10,000 Families",
    category: "Social Impact",
    author: "Maria Santos",
    date: "2024-01-15",
    readTime: "5 min read",
    image:
      "https://images.unsplash.com/photo-1541544181051-e46607bc22a4?w=400&q=80",
    excerpt:
      "A simple challenge about water access in rural Brazil led to an innovative, low-cost purification system now helping thousands of families.",
    impact: "10,000+ families with clean water access",
    solutions: 23,
    collaborators: 8,
  },
  {
    id: 2,
    title: "AI-Powered Learning Tool Transforms Special Education",
    category: "Education",
    author: "Dr. James Kim",
    date: "2024-01-10",
    readTime: "7 min read",
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&q=80",
    excerpt:
      "Teachers struggling with personalized learning for special needs students found an AI solution through community collaboration.",
    impact: "500+ students with improved learning outcomes",
    solutions: 31,
    collaborators: 12,
  },
  {
    id: 3,
    title: "Small Business Inventory Crisis Solved with Simple App",
    category: "Business",
    author: "Sarah Chen",
    date: "2024-01-05",
    readTime: "4 min read",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&q=80",
    excerpt:
      "A restaurant owner's inventory nightmare became a streamlined solution now used by 200+ small businesses.",
    impact: "200+ businesses with improved efficiency",
    solutions: 18,
    collaborators: 6,
  },
  {
    id: 4,
    title: "Community Garden Network Fights Food Insecurity",
    category: "Community",
    author: "Alex Rodriguez",
    date: "2023-12-28",
    readTime: "6 min read",
    image:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80",
    excerpt:
      "Urban food desert challenge sparked a network of community gardens that now feeds entire neighborhoods.",
    impact: "15 communities with improved food access",
    solutions: 27,
    collaborators: 15,
  },
  {
    id: 5,
    title: "Mental Health Support Platform Born from Personal Struggle",
    category: "Healthcare",
    author: "Dr. Emily Johnson",
    date: "2023-12-20",
    readTime: "8 min read",
    image:
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80",
    excerpt:
      "A therapist's challenge about patient accessibility led to a peer support platform serving thousands.",
    impact: "5,000+ people receiving mental health support",
    solutions: 42,
    collaborators: 20,
  },
  {
    id: 6,
    title: "Elderly Care Coordination System Reduces Hospital Readmissions",
    category: "Healthcare",
    author: "Michael Park",
    date: "2023-12-15",
    readTime: "5 min read",
    image:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400&q=80",
    excerpt:
      "Family caregiver's coordination challenge became a system that's reduced hospital readmissions by 30%.",
    impact: "30% reduction in hospital readmissions",
    solutions: 19,
    collaborators: 9,
  },
];

const impactStats = [
  {
    icon: <Users className="w-8 h-8" />,
    value: "1M+",
    label: "Lives Impacted",
    description:
      "People whose lives have been improved through community solutions",
  },
  {
    icon: <Lightbulb className="w-8 h-8" />,
    value: "500+",
    label: "Solutions Implemented",
    description: "Community solutions that have been successfully deployed",
  },
  {
    icon: <Globe className="w-8 h-8" />,
    value: "75+",
    label: "Countries Reached",
    description:
      "Nations where our community solutions are making a difference",
  },
  {
    icon: <Heart className="w-8 h-8" />,
    value: "$50M+",
    label: "Value Created",
    description: "Estimated economic and social value generated by solutions",
  },
];

export default function SuccessStoriesPage() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <main className="container mx-auto px-4 py-16">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold mb-6">Success Stories</h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Real challenges, real solutions, real impact. Discover how our
            community's collaborative problem-solving is changing lives and
            transforming communities around the world.
          </p>
        </div>

        {/* Impact Stats */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          {impactStats.map((stat, index) => (
            <Card key={index} className="text-center">
              <CardContent className="p-8">
                <div className="text-primary mb-4 flex justify-center">
                  {stat.icon}
                </div>
                <div className="text-3xl font-bold mb-2">{stat.value}</div>
                <div className="font-medium mb-2">{stat.label}</div>
                <div className="text-sm text-muted-foreground">
                  {stat.description}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Featured Story */}
        <Card className="mb-16 overflow-hidden">
          <div className="md:flex">
            <div className="md:w-1/2">
              <img
                src={successStories[0].image}
                alt={successStories[0].title}
                className="w-full h-64 md:h-full object-cover"
              />
            </div>
            <div className="md:w-1/2 p-8">
              <Badge className="mb-4">{successStories[0].category}</Badge>
              <h2 className="text-2xl font-bold mb-4">
                {successStories[0].title}
              </h2>
              <p className="text-muted-foreground mb-6">
                {successStories[0].excerpt}
              </p>

              <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="text-center">
                  <div className="font-semibold text-primary">
                    {successStories[0].solutions}
                  </div>
                  <div className="text-xs text-muted-foreground">Solutions</div>
                </div>
                <div className="text-center">
                  <div className="font-semibold text-primary">
                    {successStories[0].collaborators}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Collaborators
                  </div>
                </div>
                <div className="text-center">
                  <div className="font-semibold text-green-600">10K+</div>
                  <div className="text-xs text-muted-foreground">
                    Lives Impacted
                  </div>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                  <span>{successStories[0].author}</span>
                  <span>•</span>
                  <span>{successStories[0].readTime}</span>
                </div>
                <Button>
                  Read Full Story
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </div>
          </div>
        </Card>

        {/* Story Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
          {successStories.slice(1).map((story) => (
            <Card
              key={story.id}
              className="hover:shadow-lg transition-shadow cursor-pointer overflow-hidden"
            >
              <div className="aspect-video overflow-hidden">
                <img
                  src={story.image}
                  alt={story.title}
                  className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
                />
              </div>
              <CardHeader>
                <div className="flex justify-between items-start mb-2">
                  <Badge variant="secondary">{story.category}</Badge>
                  <span className="text-xs text-muted-foreground">
                    {story.readTime}
                  </span>
                </div>
                <CardTitle className="text-lg line-clamp-2 hover:text-primary transition-colors">
                  {story.title}
                </CardTitle>
                <p className="text-sm text-muted-foreground line-clamp-3">
                  {story.excerpt}
                </p>
              </CardHeader>
              <CardContent>
                <div className="bg-muted/50 rounded-lg p-3 mb-4">
                  <div className="text-sm font-medium text-green-700 mb-1">
                    Impact:
                  </div>
                  <div className="text-sm text-muted-foreground">
                    {story.impact}
                  </div>
                </div>

                <div className="flex items-center justify-between text-sm text-muted-foreground">
                  <div className="flex items-center gap-3">
                    <span>{story.solutions} solutions</span>
                    <span>•</span>
                    <span>{story.collaborators} collaborators</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    <span>{new Date(story.date).toLocaleDateString()}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* CTA Section */}
        <Card className="bg-gradient-to-r from-primary to-primary/80 text-primary-foreground text-center">
          <CardContent className="p-12">
            <h2 className="text-3xl font-bold mb-4">
              Your Challenge Could Be Next
            </h2>
            <p className="text-primary-foreground/90 mb-8 max-w-2xl mx-auto">
              Every success story started with someone brave enough to share
              their challenge. What problem are you facing that our community
              could help solve?
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" variant="secondary">
                Share Your Challenge
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="bg-transparent border-primary-foreground text-primary-foreground hover:bg-primary-foreground hover:text-primary"
              >
                Browse Current Challenges
              </Button>
            </div>
          </CardContent>
        </Card>
      </main>

      <Footer />
    </div>
  );
}
